# Site settings
title: rubycorns.club | The fabulous rubycorns
email: rubycorns@googlegroups.com
description: The Rails Girls studygroup meeting on Tuesdays in Berlin
baseurl: "/jekyll/" # the subpath of your site, e.g. /blog/
url: "http://rubycorns.club" # the base hostname & protocol for your site
twitter_username: rubycorns
github_username:  rubycorns

# Build settings
markdown: kramdown
